const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const ROOT=path.resolve(__dirname,'..');const DATA=path.join(__dirname,'data','users.json');const PORT=process.env.PORT||3000;const sessions=new Map();
function readUsers(){try{return JSON.parse(fs.readFileSync(DATA,'utf8'))}catch{return []}}function writeUsers(u){fs.writeFileSync(DATA,JSON.stringify(u,null,2))}
function hash(password,salt=crypto.randomBytes(16).toString('hex')){const digest=crypto.scryptSync(password,salt,64).toString('hex');return {salt,hash:digest}}
function verify(password,salt,stored){try{return crypto.timingSafeEqual(Buffer.from(hash(password,salt).hash,'hex'),Buffer.from(stored,'hex'))}catch{return false}}
function parseCookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}))}
function send(res,status,data,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8',...headers});res.end(JSON.stringify(data))}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1e6)req.destroy()});req.on('end',()=>{try{resolve(JSON.parse(s||'{}'))}catch{reject(new Error('Invalid JSON'))}});req.on('error',reject)})}
function validEmail(e){return typeof e==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)}
function sessionCookie(id){return `sid=${encodeURIComponent(id)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml','.ico':'image/x-icon'};
const server=http.createServer(async(req,res)=>{try{
 if(req.url==='/api/auth/signup'&&req.method==='POST'){const d=await body(req);const firstName=String(d.firstName||'').trim(),lastName=String(d.lastName||'').trim(),email=String(d.email||'').trim().toLowerCase(),password=String(d.password||'');if(!firstName||!lastName||!validEmail(email)||password.length<6)return send(res,400,{error:'Please enter a valid name, email and a password of at least 6 characters.'});const users=readUsers();if(users.some(u=>u.email===email))return send(res,409,{error:'An account with this email already exists. Please sign in instead.'});const p=hash(password);const user={id:crypto.randomUUID(),firstName,lastName,email,passwordHash:p.hash,passwordSalt:p.salt,createdAt:new Date().toISOString()};users.push(user);writeUsers(users);const sid=crypto.randomBytes(32).toString('hex');sessions.set(sid,{userId:user.id,expires:Date.now()+604800000});return send(res,201,{ok:true,user:{id:user.id,firstName,lastName,email}},{'Set-Cookie':sessionCookie(sid)});}
 if(req.url==='/api/auth/login'&&req.method==='POST'){const d=await body(req);const email=String(d.email||'').trim().toLowerCase(),password=String(d.password||'');const user=readUsers().find(u=>u.email===email);if(!user||!verify(password,user.passwordSalt,user.passwordHash))return send(res,401,{error:'Incorrect email or password.'});const sid=crypto.randomBytes(32).toString('hex');sessions.set(sid,{userId:user.id,expires:Date.now()+604800000});return send(res,200,{ok:true,user:{id:user.id,firstName:user.firstName,lastName:user.lastName,email:user.email}},{'Set-Cookie':sessionCookie(sid)});}
 if(req.url==='/api/auth/logout'&&req.method==='POST'){const c=parseCookies(req);sessions.delete(c.sid);return send(res,200,{ok:true},{'Set-Cookie':'sid=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'});}
 if(req.url==='/api/auth/me'&&req.method==='GET'){const c=parseCookies(req),s=sessions.get(c.sid);if(!s||s.expires<Date.now())return send(res,401,{authenticated:false});const u=readUsers().find(x=>x.id===s.userId);if(!u)return send(res,401,{authenticated:false});return send(res,200,{authenticated:true,user:{id:u.id,firstName:u.firstName,lastName:u.lastName,email:u.email}})}
 let pathname=new URL(req.url,'http://localhost').pathname;if(pathname==='/')pathname='/index.html';const file=path.normalize(path.join(ROOT,pathname));if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return send(res,404,{error:'Not found'});const ext=path.extname(file).toLowerCase();res.writeHead(200,{'Content-Type':mime[ext]||'application/octet-stream'});fs.createReadStream(file).pipe(res);
 }catch(e){console.error(e);send(res,500,{error:'Server error.'})}});
server.listen(PORT,()=>console.log(`Sequencer running at http://127.0.0.1:${PORT}`));
